# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Jade Treasury
description: >- # this means to ignore newlines until "baseurl:"
  This website is an extension of a group called "The Jade Palace". The Jade Palace is a project started by a few like-minded individuals who met through the Zen forum over at www.reddit.com/r/zen. (https://www.reddit.com/r/zen/)
  Now a bit about ourselves
  We are a small group focused on inter-personal learning. Our core focus regards the study of Zen, but our group’s design is to serve as a resource for its members, so we also have a mission that is interested in more general matters of humanism, spirituality, and personal well-being as well.
  In the Zen literature, one finds the following story
  A monk, having received an awakening blow from Master YunMen, declared
  "Hereafter I'll go to a place where there are no human hearths and will build myself a grass hut. I won't grow a single grain of rice nor store a single bunch of vegetables, and I will receive the sages that will come and go from all directions. I'll pull out the nails and pegs for them, tear off their greasy hats, strip off their stinking jackets, and I'll see to it that they get clean and free and become patch-robed monks!”_
  In China, and most of Southern Asia in general, there is an old tradition of mendicants going into the caves and grottos of mountains, as well as building simple grass huts there, in order to seek solitude and meditate on the nature of mind.
  Our groups project is inspired by those projects of the ancient medicants. So we’ve made this website as a way to share the results and scraps of our mutual efforts with the Internet. We hope you’ll find something of value for yourself among our offerings here.
  Welcome to the Jade Treasury.

baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

Build settings:
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
